### ISSUE TITLE
scaleImage provided to fit the canvas

### ISSUE THREAD

**Issue by MagnusThor** [VirtualScenery/greenscreenstream#27]
When setting the image, we should resize to canvas size in order to speed up things, if a large custom image is provided rendering is slow.

If canvas is set to SD 16:9  , 640 x 360 image should be resized;  below working code i use kollokium,   @BIueLightning  can you  implement it ?  in the init method as well as in `setBackground():void ` 

  ```
  scaleImage(image: HTMLImageElement): Promise<HTMLImageElement> {
        return new Promise<HTMLImageElement>((resolve, reject) => {
            createImageBitmap(image, {
                resizeWidth: this.canvas.width
                , resizeHeight: this.canvas.height, resizeQuality: 'high'
            }).then(bm => {
                const canvas = document.createElement('canvas');

                canvas.width = bm.width;
                canvas.height = bm.height;


                console.log(`${bm.width} x ${bm.height} is the image size`)
        

                const ctx = canvas.getContext('bitmaprenderer');
                ctx.transferFromImageBitmap(bm);
                canvas.toBlob(blob => {
                    var img = document.body.appendChild(new Image());
                    img.src = URL.createObjectURL(blob);
                    resolve(img);
                });
            }).catch(reject)
        });
    }

```

**Comment by BIueLightning** [comment]
Done: [ad8aeca](https://github.com/coloquium/greenscreenstream/commit/ad8aeca00f07c92f916592088509a5e11b10341d)

Needs testing

**Comment by MagnusThor** [comment]
Okey, lets the things we talked about, and the we do a laso beta release where we do final tests upon.

**Comment by BIueLightning** [comment]
Renderer had a line break in shader header declaration, stopped the whole package from functioning: [d3f04f7](https://github.com/coloquium/greenscreenstream/commit/d3f04f7b2116ee7b55c84cdd787fe2cff1feab7a)
Examples are updated now aswell.
I think we are ready now, yes :)
